import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Tailwind Playground</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen">
        <ul>
          <li>
            <Link href="/grid">
              <a>Grid Example</a>
            </Link>
          </li>
          <li>
            <Link href="/theming-with-css-variables">
              <a>Theming with CSS Variables</a>
            </Link> Based on: https://www.youtube.com/watch?v=MAtaT8BZEAo
          </li>
        </ul>
      </main>
    </div>
  )
}
